export const tableBody = [
    {
        name: "Shafin Riaz",
        id: "#01",
        duration: "2 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1200.00",
        grow: true,
    },
    {
        name: "Banna",
        id: "#02",
        duration: "3 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1800.00",
        grow: false,
    },
    {
        name: "Omor",
        id: "#03",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
    {
        name: "Faruk",
        id: "#04",
        duration: "4 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 2400.00",
        grow: false,
    },
    {
        name: "Iqbla",
        id: "#05",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
    {
        name: "Shafin Riaz",
        id: "#01",
        duration: "2 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1200.00",
        grow: true,
    },
    {
        name: "Banna",
        id: "#02",
        duration: "3 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1800.00",
        grow: false,
    },
    {
        name: "Omor",
        id: "#03",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
    {
        name: "Faruk",
        id: "#04",
        duration: "4 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 2400.00",
        grow: false,
    },
    {
        name: "Iqbla",
        id: "#05",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
];
export const tableHeader = [
    { label: " Serial no." },
    { label: " details" },
    { label: "duration" },
    { label: "amount" },
    { label: "total balance" },
];
export const adminTeachertableHeader = [
    { label: "Serial no." },
    { label: "details" },
    { label: "date" },
    { label: "amount" },
];
export const adminTeacherTableBody = [
    {
        name: "Shafin Riaz",
        id: "#01",
        duration: "11-09-2021",
        amount: " Tk. 600",
        grow: true,
    },
    {
        name: "Banna",
        id: "#02",
        duration: "11-09-2021",
        amount: " Tk. 500",
        grow: false,
    },
    {
        name: "Omor",
        id: "#03",
        duration: "11-09-2021",
        amount: " Tk. 1000",
        grow: true,
    },
    {
        name: "Faruk",
        id: "#04",
        duration: "11-09-2021",
        amount: " Tk. 400",
        grow: false,
    },
    {
        name: "Iqbla",
        id: "#05",
        duration: "11-09-2021",
        amount: " Tk. 200",
        grow: true,
    },
    {
        name: "Shafin Riaz",
        id: "#01",
        duration: "11-09-2021",
        amount: " Tk. 700",
        grow: true,
    },
    {
        name: "Banna",
        id: "#02",
        duration: "11-09-2021",
        amount: " Tk. 500",
        grow: false,
    },
    {
        name: "Omor",
        id: "#03",
        duration: "11-09-2021",
        amount: " Tk. 300",
        grow: true,
    },
    {
        name: "Faruk",
        id: "#04",
        duration: "11-09-2021",
        amount: " Tk. 600",
        grow: false,
    },
    {
        name: "Iqbla",
        id: "#05",
        duration: "11-09-2021",
        amount: " Tk. 400",
        grow: true,
    },
];
export const chatUser = [
    {
        userName: "Rifa Haque Afi",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: true,
    },
    {
        userName: "Hasanul Haque Banna",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: false,
    },
    {
        userName: "Afiya akter",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: false,
    },
    {
        userName: "Moyashin Iqbal",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: true,
    },
    {
        userName: "Rifa Haque Afi",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: true,
    },
    {
        userName: "Hasanul Haque Banna",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: false,
    },
    {
        userName: "Afiya akter",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: false,
    },
    {
        userName: "Moyashin Iqbal",
        lastSee: "Last seen at 5:32",
        message: "You: Bhaiya kalke 5 tay set koro",
        currentTime: "(6:15 pm)",
        activeUser: true,
    },
];

export const adminstudentinfo = [
    {
        label: "Ruhul Amin Tusar",
        email: "writeRuhul@gmail.com",
        number: "01824696930",
    },
    {
        label: "Amin Tusar",
        email: "amin@gmail.com",
        number: "018246979790",
    },
    {
        label: "Tusar",
        email: "writetusar@gmail.com",
        number: "01724696930",
    },
    {
        label: "Ruhul",
        email: "Ruhul@gmail.com",
        number: "0182479790",
    },
    {
        label: "Ruhul Tusar",
        email: "writeRuhulTusar@gmail.com",
        number: "01709876930",
    },
    {
        label: "Tusar Amin",
        email: "Tusaramin@gmail.com",
        number: "018242329790",
    },
    {
        label: "Amin",
        email: "writetusarAmin@gmail.com",
        number: "01578996930",
    },
    {
        label: "Ratul",
        email: "Ratul@gmail.com",
        number: "0191111979790",
    },
    {
        label: "banna",
        email: "writebanna@gmail.com",
        number: "01689798730",
    },
    {
        label: "Rahat",
        email: "Rahat@gmail.com",
        number: "0130988979",
    },
    {
        label: "iqbal",
        email: "writeiqbal@gmail.com",
        number: "0146969816",
    },
    {
        label: "Rakib",
        email: "Rakib@gmail.com",
        number: "0152469799870",
    },
    {
        label: "Omor",
        email: "writeOmor@gmail.com",
        number: "01429876530",
    },
    {
        label: "Afrime",
        email: "Afrime@gmail.com",
        number: "013247654780",
    },
    {
        label: "ali",
        email: "writeali@gmail.com",
        number: "01524876690",
    },
    {
        label: "akash",
        email: "akash@gmail.com",
        number: "01912349790",
    },
];
