export const tableBody = [
    {
        name: "Shafin Riaz",
        id: "#01",
        duration: "2 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1200.00",
        grow: true,
    },
    {
        name: "Banna",
        id: "#02",
        duration: "3 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1800.00",
        grow: false,
    },
    {
        name: "Omor",
        id: "#03",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
    {
        name: "Faruk",
        id: "#04",
        duration: "4 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 2400.00",
        grow: false,
    },
    {
        name: "Iqbla",
        id: "#05",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
    {
        name: "Shafin Riaz",
        id: "#01",
        duration: "2 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1200.00",
        grow: true,
    },
    {
        name: "Banna",
        id: "#02",
        duration: "3 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 1800.00",
        grow: false,
    },
    {
        name: "Omor",
        id: "#03",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
    {
        name: "Faruk",
        id: "#04",
        duration: "4 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 2400.00",
        grow: false,
    },
    {
        name: "Iqbla",
        id: "#05",
        duration: "1 hours",
        amount: " Tk. 600.00",
        totalbalance: " Tk. 600.00",
        grow: true,
    },
];
export const tableHeader = [
    { label: " Serial no." },
    { label: " details" },
    { label: "duration" },
    { label: "amount" },
    { label: "total balance" },
];
