const {
  REACT_APP_PRODUCTION_SERVER_URL,
  REACT_APP_DEVELOPMENT_SERVER_URL,
  REACT_APP_NODE_ENV,
  REACT_APP_PRODUCTION_SOCKET_URL,
  REACT_APP_DEVELOPMENT_SOCKET_URL,
} = process.env;

export const PRODUCTION_API_URL = REACT_APP_PRODUCTION_SERVER_URL;
export const DEVELOPMENT_API_URL = REACT_APP_DEVELOPMENT_SERVER_URL;
export const PRODUCTION_SOCKET_URL = REACT_APP_PRODUCTION_SOCKET_URL;
export const DEVELOPMENT_SOCKET_URL = REACT_APP_DEVELOPMENT_SOCKET_URL;
export const NODE_ENV = REACT_APP_NODE_ENV;
